#Minecraft server properties
#Mon May 11 16:20:42 EDT 2026
spawn-protection=0
max-tick-time=600000
query.port=9898
generator-settings=
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=30
difficulty=2
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=default
hardcore=false
enable-command-block=true
network-compression-threshold=256
max-players=100
resource-pack-sha1=
max-world-size=29999984
server-port=41729
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=5
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=false
max-build-height=256
level-seed=
prevent-proxy-connections=false
use-native-transport=true
enable-rcon=false
motd=\u00A77Welcome to the server of \u00A79SpyderSammyjpg\u00A77\!
